spring.application.name=backend
#yandex
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

yandex.bucket=${YANDEX_BUCKET}
yandex.access-key=${YANDEX_ACCESS_KEY}
yandex.secret-key=${YANDEX_SECRET_KEY}


#db
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SQL init configuration
spring.sql.init.mode=always
#minio
minio.endpoint=http://minio:9000
minio.access-key=minioadmin
minio.secret-key=password
minio.bucket-name=bucket
minio.secure=false